"""A module to hold globally relevant constants"""

SCREEN_WIDTH = 256
SCREEN_HEIGHT = 256

ICON_WIDTH = 16
ICON_HEIGHT = 16

INVENTORY_BOX_BORDER_THICKNESS = 2
NUM_INVENTORY_BOXES = 8
NUM_SOCIETAL_BOXES = 3
